## 网站设置
# 站点基本信息
title: 小豌先生的随笔日志
# 选项卡标题
SEOTitle: 梵高投研风口 | 小豌先生's Blog
# 首页背景图片
header-img: img/site/post-bg-debug.png
# 邮箱设置
email: xiao2683@gmail.com
# 网站介绍
description: "分享投资笔记、AI与生活随想"
# 关键词
keyword: "投资, Swift, iOS, Vue.js, Apple, iPhone, AI, 技术, 生活"
# 博客访问链接
url: "https://xiaoallocinit.github.io/xiaowanBlog.github.io/"
# baseurl should be empty for user pages or project name for project pages
baseurl: "/xiaowanBlog.github.io"

# 作者信息
author:
  name: 小豌先生
  email: xiao2683@gmail.com
  github: xiaoallocinit

## 侧边栏设置
# 是否开启侧边栏 true 开始 false 关闭
sidebar: true
# 侧边栏描述语句
sidebar-about-description: "顺势"
# 侧边栏头像
sidebar-avatar: /img/site/sidebar-avatar.jpg

## 社交网站设置
RSS: false

## 构建设置
permalink: pretty
paginate: 10
paginate_path: "/page:num/"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

## Plugins
# Jekyll plugins for GitHub Pages compatibility
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Legacy gems support (for older Jekyll versions)
gems:
  - jekyll-paginate

## Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown